###
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal-mysql
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal-mysql
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
      containers:
      - image: mysql:5.7
        name: mysql
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: task-pv-storage
            subPath: dbdata
        ##
        ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP

        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_USER

          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_ROOT_PASSWORD

          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: drupal-mysql-secret
                key: MYSQL_DATABASE

---

## drupal-mysql-service

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drupal-mysql
  name: drupal-mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: drupal-mysql
  type: ClusterIP
status:
  loadBalancer: {}
